### ISSUE TITLE
Typo in nec_context.cpp

### ISSUE THREAD

**Issue by ytakeyasu** [tmolteno/necpp#11]
Hi,

nec_context.cpp
```
2959 cw[jx*ipr*nw] += etk* m_geometry->ax[ij]+ ets* m_geometry->bx[ij]+ etc* m_geometry->cx[ij];
```
The "jx*" might be "jx+".
```
2959 cw[jx+ipr*nw] += etk* m_geometry->ax[ij]+ ets* m_geometry->bx[ij]+ etc* m_geometry->cx[ij];
```
Regards.

Yoshi Takeyasu

**Comment by ytakeyasu** [comment]
Hi again,

I'm wondering also if "nw" is "nr" or not.
```
2959 cw[jx+ipr*nw] += etk* m_geometry->ax[ij]+ ets* m_geometry->bx[ij]+ etc* m_geometry->cx[ij];
```
or
```
2959 cw[jx+ipr*nr] += etk* m_geometry->ax[ij]+ ets* m_geometry->bx[ij]+ etc* m_geometry->cx[ij];
```

Thank you.

Yoshi Takeyasu

**Comment by tmolteno** [comment]
Hi Yoshi

Thank you for pointing these out. I will have a look and get back to you.

Kind Regards

Tim Molteno

**Comment by tmolteno** [comment]
You are correct with this one. I have modified it to jx+ipr*nr

I will create a testbench to verify any changes to the output.

Kind Regards

Tim

**Comment by tmolteno** [comment]
Testbench  completed.
