### ISSUE TITLE
Ruby-Module - Wrong path in swig file

### ISSUE THREAD

**Issue by marc-hendry** [tmolteno/necpp#22]
Using the **build.sh** script works fine, but trying to compile the Ruby module using swig will fail. Seems to be a faulty path to `src/libnecpp.h`

```
marc@ubuntu-12.04-LTS:~/necpp/Ruby/ext/necpp$ swig -v -c++ -ruby necpp.i

Language subdirectory: ruby
Search paths:
   ./
   ./swig_lib/ruby/
   /usr/share/swig2.0/ruby/
   ./swig_lib/
   /usr/share/swig2.0/
Preprocessing...
necpp.i:49: Error: Unable to find '../src/libnecpp.h'
```

**Comment by tmolteno** [comment]
Thank you for the report. I have made the path specification consistent (it was not well specified). Now the path to libnecpp.h has to be specified on the command line when using swig. Can you let me know if this works?

Kind Regards

Tim

**Comment by marc-hendry** [comment]
Thanks, it works fine now.
