### ISSUE TITLE
osx build with accelerate framework any success?

### ISSUE THREAD

**Issue by gaming-hacker** [tmolteno/necpp#27]
i'm trying to link this against apple's accelerate framework but this program complains about not finding lapack libs when i know they in the library.

i've made progress but had to heavily modify the configure,  this is osx not linux and it wouldn't recognize proper paths.

but there are a lot of these warnings
/src/nec_context.cpp:3886:8: warning: use of unary operator that may be intended as compound assignment (-=)
    rfl=- rfl;
       ^~
i fixed these as well.

i have binaries and libs now but i pretty much had to edit the makefile by hand.

when i correct this warning, abs is for integers not floats
c_evlcom_tb.cpp:14:15: note: use function 'std::abs' instead
     REQUIRE((abs(j0.real() -  j0r) < eps));
              ^~~

**Comment by jeffsf** [comment]
See #30 resolved by #33 as well as an abs() problem #32 resolved by #34 

Working on LAPACK(7) which redirects to ACCELERATE(7) next...

**Comment by tmolteno** [comment]
Good work. I'm catching up on issues after a break.  Will try and take these one by one and commit the changes. 

Kind regards 
Tim
