### ISSUE TITLE
Build files because of -Werror (misleading indentation).

### ISSUE THREAD

**Issue by felixbecker2** [tmolteno/necpp#39]
The problem is within the build process:

`In file included from safe_array_tb.cpp:20:0:
catch.hpp: In member function ‘bool Catch::TestSpec::Filter::matches(const Catch::TestCaseInfo&) const’:
catch.hpp:2813:17: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
                 for( std::vector<Ptr<Pattern> >::const_iterator it = m_patterns.begin(), itEnd = m_patterns.end(); it != itEnd; ++it )
                 ^~~
catch.hpp:2816:21: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
                     return true;
                     ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:950: test_manager-safe_array_tb.o] Error 1
make[2]: Leaving directory '[...]/necpp/src'
make[1]: *** [Makefile:469: all-recursive] Error 1
make[1]: Leaving directory '[...]/src/necpp'
make: *** [Makefile:378: all] Error 2`

Patch below fixes it for me:

`diff -U2 -r necpp.orig/src/catch.hpp necpp.new/src/catch.hpp
--- necpp.orig/src/catch.hpp    2016-11-01 10:16:39.000000000 +0100
+++ necpp.new/src/catch.hpp     2016-11-01 10:24:15.000000000 +0100
@@ -2814,5 +2814,5 @@
                     if( !(*it)->matches( testCase ) )
                         return false;
-                    return true;
+                return true;
             }
         };
`

Alternatively, one could fix the Makefiles to add `-Wno-error=misleading-indentation` to work around that problem.

**Comment by tmolteno** [comment]
I have updated to the latest catch.hpp. This issue no longer appears.
