### ISSUE TITLE
Build fails with `call of overloaded ‘abs(double)’ is ambiguous`

### ISSUE THREAD

**Issue by felixbecker2** [tmolteno/necpp#40]
After fixing `-Werror`-triggered errors, the build files due to a more substantial error:

`In file included from c_evlcom_tb.cpp:1:0:
c_evlcom_tb.cpp: In function ‘void test_bessel(nec_float, nec_float, nec_float, nec_float)’:
c_evlcom_tb.cpp:14:35: error: call of overloaded ‘abs(double)’ is ambiguous
      REQUIRE((abs(j0.real() -  j0r) < eps));
`

I cannot fix that, since I do next to nothing about C/ C++.

**Comment by tmolteno** [comment]
I think this might now be fixed. I think this issue is related to the clang compiler (often used on Macs).
