### ISSUE TITLE
How to get the magnitude and phase of the radiation patterns with the python interface

### ISSUE THREAD

**Issue by swissel** [tmolteno/necpp#44]
I'd like to access the get_etheta/phi_magnitude and get_etheta/phi_phase complex radiation patterns. Is there a way to do this with the python interface? So far I've tried both nec_etheta_magnitude and get_etheta_magntiude, but neither are recognized.

For instance:
  etheta = []
  ephi = []
  for it in range(len(thetas)):
	t = []
	p = []
	for ip in range(len(phis)):
		t.append(get_etheta_magnitude(nec, 0, it, ip) + 1j* get_etheta_phase(nec, 0, it, ip))
		p.append(get_ephi_magnitude(nec, 0, it, ip) + 1j*get_ephi_phase(nec, 0, it, ip))
	etheta.append(np.array(t))

  etheta = []
  ephi = []
  for it in range(len(thetas)):
	t = []
	p = []
	for ip in range(len(phis)):
		t.append(nec_etheta_magnitude(nec, 0, it, ip) + 1j* nec_etheta_phase(nec, 0, it, ip))
		p.append(nec_ephi_magnitude(nec, 0, it, ip) + 1j*nec_ephi_phase(nec, 0, it, ip))
	etheta.append(np.array(t))

**Comment by tmolteno** [comment]
Using the python-necpp module (pip install necpp), this is not currently possible. The only gain is in dB.

Using the PyNEC module (pip install PyNEC) there is a get_etheta_magnitude() and get_etheta_phase() method on the radiation pattern object.
